AllCops:
  TargetRubyVersion: 2.6
ClassLength:
  Max: 150
Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Max: 35
Metrics/MethodLength:
  Max: 15
Documentation:
  Enabled: false
Naming/FileName:
  Enabled: false
